# Generated by Django 2.0 on 2017-12-09 22:48

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroupeXClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privkey', models.CharField(max_length=40, unique=True)),
                ('name', xorgauth.utils.fields.UnboundedCharField(unique=False)),
                ('datafields', xorgauth.utils.fields.UnboundedCharField()),
                ('returnurls', xorgauth.utils.fields.UnboundedCharField()),
                ('last_used', models.DateField(null=True)),
                ('allow_xnet', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AuthGroupeX client',
                'verbose_name_plural': 'AuthGroupeX clients',
            },
        ),
    ]
