# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authgroupex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authgroupexclient',
            old_name='datafields',
            new_name='data_fields',
        ),
        migrations.RenameField(
            model_name='authgroupexclient',
            old_name='returnurls',
            new_name='return_urls',
        ),
    ]
