# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authgroupex', '0002_make_field_names_coherent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authgroupexclient',
            name='allow_xnet',
            field=models.BooleanField(default=False,
                                      help_text="Allow account with type 'xnet' (external) to log in to this client",
                                      verbose_name='allow xnet'),
        ),
        migrations.AlterField(
            model_name='authgroupexclient',
            name='data_fields',
            field=xorgauth.utils.fields.UnboundedCharField(help_text='Fields requested by the client',
                                                           verbose_name='data fields'),
        ),
        migrations.AlterField(
            model_name='authgroupexclient',
            name='last_used',
            field=models.DateField(help_text='Date of the last use of this client', null=True,
                                   verbose_name='last used'),
        ),
        migrations.AlterField(
            model_name='authgroupexclient',
            name='name',
            field=xorgauth.utils.fields.UnboundedCharField(help_text='Name of the client', unique=False,
                                                           verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='authgroupexclient',
            name='privkey',
            field=models.CharField(help_text='Secret key shared with the client', max_length=40, unique=True,
                                   verbose_name='private key'),
        ),
        migrations.AlterField(
            model_name='authgroupexclient',
            name='return_urls',
            field=xorgauth.utils.fields.UnboundedCharField(
                help_text='Regular expression pattern of the allowed return URLs', verbose_name='return URLs'),
        ),
    ]
