# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 14:32
from __future__ import unicode_literals

from django.db import migrations
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authgroupex', '0003_add_verbose_and_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authgroupexclient',
            name='name',
            field=xorgauth.utils.fields.UnboundedCharField(help_text='Name of the client', verbose_name='name'),
        ),
    ]
