# Generated by Django 2.0.3 on 2018-03-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authgroupex', '0004_make_UnboundedCharField_non_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authgroupexclient',
            name='last_used',
            field=models.DateField(blank=True, help_text='Date of the last use of this client', null=True,
                                   verbose_name='last used'),
        ),
    ]
