# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.SlugField(unique=True, verbose_name='short name')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.SlugField(choices=[('member', 'member'), ('admin', 'administrator')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='groups', to=settings.AUTH_USER_MODEL, verbose_name='groups')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='members', to='accounts.Group', verbose_name='members')),
            ],
        ),
    ]
