# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_groupmembership_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hrid',
            field=models.SlugField(unique=True, verbose_name='username'),
        ),
    ]
