# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_better_user-facing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='axid',
            field=xorgauth.utils.fields.UnboundedCharField(
                help_text='Identification in AX directory', null=True, verbose_name='AX ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='grad_year',
            field=models.IntegerField(help_text='Year of the graduation', null=True, verbose_name='graduation year'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_year',
            field=xorgauth.utils.fields.UnboundedCharField(
                help_text="Kind and main year of the study ('X1829' means 'entered the school in 1829 "
                "but 'M2005' means 'graduated in 2005')", null=True, verbose_name='study year'),
        ),
    ]
