# Generated by Django 2.0 on 2017-12-09 21:48

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_axid_and_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=xorgauth.utils.fields.UnboundedCharField(null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=xorgauth.utils.fields.UnboundedCharField(null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')],
                                   max_length=6, null=True, verbose_name='sex'),
        ),
    ]
