# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 18:14
from __future__ import unicode_literals

from django.db import migrations
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_xorg_and_school_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hrid',
            field=xorgauth.utils.fields.DottedSlugField(
                help_text='Human-readable identifier, usually firstname.lastname.study-year',
                max_length=255, unique=True, verbose_name='username'),
        ),
    ]
