# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_user_ids_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active user', verbose_name='active'),
        ),
    ]
