# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_user_ids_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=xorgauth.utils.fields.UnboundedCharField(blank=True, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=xorgauth.utils.fields.UnboundedCharField(blank=True, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6,
                                   null=True, verbose_name='sex'),
        ),
    ]
