# Generated by Django 2.0.1 on 2018-01-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_make_user_ids_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
    ]
