# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_make_user_names_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='display',
            field=xorgauth.utils.fields.UnboundedCharField(verbose_name='display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='axid',
            field=models.CharField(blank=True, help_text='Identification in AX directory', max_length=20, null=True,
                                   unique=True, verbose_name='AX ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schoolid',
            field=models.CharField(blank=True, help_text='Identification defined by the School', max_length=20,
                                   null=True, unique=True, verbose_name='School ID'),
        ),
    ]
