# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_is_active_field'),
        ('accounts', '0013_make_UnboundedCharField_non_unique'),
    ]

    operations = [
    ]
