# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xorgauth.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_reset_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAppsPassword',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              primary_key=True,
                                              related_name='gapps_password',
                                              serialize=False,
                                              to=settings.AUTH_USER_MODEL,
                                              verbose_name='user')),
                ('password', xorgauth.utils.fields.UnboundedCharField(verbose_name='password')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Apps password',
                'verbose_name_plural': 'Google Apps passwords',
            },
        ),
    ]
