# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_missing_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alumnforce_id',
            field=models.CharField(blank=True, help_text='User ID in ax.polytechnique.org database', max_length=20,
                                   null=True, unique=True, verbose_name='AlumnForce ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AddField(
            model_name='user',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='death date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='dead'),
        ),
    ]
