# Generated by Django 3.1.14 on 2025-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_ax_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ax_contributor',
            field=models.BooleanField(blank=True, help_text='Paid a contribution to AX', null=True, verbose_name='AX contributor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='axjr_subscriber',
            field=models.BooleanField(blank=True, help_text='Subscribed to La Jaune et la Rouge,', null=True, verbose_name='J&R subscriber'),
        ),
    ]
